### ISSUE TITLE
Add support for new Authenticode Cert

### ISSUE THREAD

**Issue by moz-hwine** [mozilla-services/fx-sig-verify#12]
[Bug 1366012](https://bugzilla.mozilla.org/show_bug.cgi?id=1366012) tracks the issuance and deployment of a new Authenticode certificate for Mozilla Windows binaries. As of 2017-07-11, it is in use for Nightly builds, and will be used for Beta as of 56.0a1b10.

Add support for this new certificate.

**Comment by hwine** [comment]
fixed with f507b4a5bfb22448ea3e016197b777b1f7a28d80
