### ISSUE TITLE
Add detection of "new filtered exe" with email notification

### ISSUE THREAD

**Issue by hwine** [mozilla-services/fx-sig-verify#19]
I believe this will require a 2nd SNS queue, but we don't want this output to go to pagerduty!

Steps:
- [ ] determine location of know exceptions (config file or database or ...)
- [ ] implement known exceptions
- [ ] major deploy changes needed

**Comment by Micheletto** [comment]
@hwine what's your timeline for this?  Adding another SNS topic, and environment var is pretty simple.

**Comment by hwine** [comment]
@Micheletto I'm doing a triage session now -- I'll send an email with the plan when I'm done. I know it's not big, just needs more coordination than me fixing a papercut ;)

**Comment by hwine** [comment]
insufficient context to reconstruct :/
