### ISSUE TITLE
Read access needed to production cloudwatch logs for fx-sig-verify

### ISSUE THREAD

**Issue by hwine** [mozilla-services/fx-sig-verify#38]
Current practice is to ask ops (bobm) to pull logs as needed. That's painful due to the volume of log data.

Ideally, a dev (me for now) would be able to pull logs directly. The download process is already scripted in [get-cloudwatch-logs](/mozilla-services/fx-sig-verify/blob/master/src/scripts/get-cloudwatch-logs).

Read access is needed to:
 region: us-east-1
 prefix: /aws/lambda/fx-sig-verify-prod

**Comment by jvehent** [comment]
@oremj , @Micheletto : this is a situation where developer (@hwine) would like limited access to cloudservices-aws-prod to read cloudwatch logs issued by a lambda function. How should this be implemented? (hal doesn't have a prod aws account)

**Comment by Micheletto** [comment]
> How should this be implemented? (hal doesn't have a prod aws account)

I think we should manage it in [userplex](https://mana.mozilla.org/wiki/display/SVCOPS/AWS%3A+How+to+manage+users) but it's not immediately obvious to me if it's easy to specify arbitrary access policies.

**Comment by jvehent** [comment]
We could have an aws group that grants the exact permissions we need, map that to an ldap group, and let userplex manage membership.

But, that's a lot of setup for something only one person needs. The next developer will need access to different resources, and thus a different ldap group, userplex config, etc.

**Comment by oremj** [comment]
Let's just create him a one off account with access to assume a role that has access to do the needed operations.

**Comment by jvehent** [comment]
talked about this today, here's the outcome:

1. as part of the resources stack, create a policy that grants access to the logs in S3
2. as part of userplex, create users that aren't in any particular groups
3. manually, give the user `hwine` access to the policy so he can read logs from s3

**Comment by jvehent** [comment]
Done.
