### ISSUE TITLE
Please deploy v0.4.7 of fx-sig-verify to production (HotFix)

### ISSUE THREAD

**Issue by hwine** [mozilla-services/fx-sig-verify#47]
Release is now releasing [nightly ASAN builds](https://bugzilla.mozilla.org/show_bug.cgi?id=1386297), which are [significantly bigger](https://bugzilla.mozilla.org/show_bug.cgi?id=1477434). This patch bumps the allowed binary size to match RelEng's new value.

Latest production push was v0.4.5 (I burned v0.4.6 rushing this patch). _[v0.5.0 had been pushed to stage, but not production (it supports additional features)]_

v0.4.7 should build and deploy cleanly.

**Comment by milescrabill** [comment]
This has been deployed to production.
