### ISSUE TITLE
Verify MAR signatures in fx_sig_verify

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/fx-sig-verify#51]
- [x] Implement functionality and dev test
- [x] Deploy to staging
- [ ] Let soak for several staging releases (days)
- [ ] deploy to prod

**Comment by hwine** [comment]
transfered

**Comment by icaropires** [comment]
Is this complete? What does still needing to do?

**Comment by hwine** [comment]
It is not complete. I'll have to pull some logs from stage to see if the new code path has been exercised.
