### ISSUE TITLE
Rewrite for Python 3

### ISSUE THREAD

**Issue by hwine** [mozilla-services/fx-sig-verify#55]
This is back burner, low priority work. This issue is mostly to catalog references to replacements for the unmaintained python2 libraries used. (Most significanly, ``verify_sigs``.)

**Comment by hwine** [comment]
[Signify](https://pypi.org/project/signify/) looks like the successor to ``verify_sigs``.

**Comment by imskr** [comment]
I would like to work on it as part of GSoC 2020. @hwine

**Comment by victorphoenix3** [comment]
@hwine Hi! I would like to work on this as a part of GSoC 20

**Comment by hwine** [comment]
Please ask questions in the matrix room
https://chat.mozilla.org/#/room/#GSOC2020:mozilla.org -- you can mention me
(@hwine) if the question is specifically about fx-sig-verify

**Comment by hwine** [comment]
Bumping priority as AWS is [dropping support for py27 in lambda](https://aws.amazon.com/blogs/compute/continued-support-for-python-2-7-on-aws-lambda/) on 2021-06-01.

We need to verify the investment first.

**Comment by hwine** [comment]
closed with 28b92d9f2fab585a2fd35c61d83fd7ed0a981691
