### ISSUE TITLE
Errors while running tests

### ISSUE THREAD

**Issue by nightwarriorftw** [mozilla-services/fx-sig-verify#72]
After setting up the development environment, I ran pytest (which is a local test runner used here) but got too many import errors. 

## How to obtain ?
Setup development environment and run `py.test tests`.

## Results ?
https://paste.mozilla.org/bCb8ghi7
(This paste is only valid upto next 21 days)
## Expected results
Test should work if development environment is correctly setup.

According to @hwine, its a documentation bug

**Comment by hwine** [comment]
It is a doc bug :(  The last step of setting up a development environment is missing. It should be:
```bash
pip install --editable .
```

That should get you going -- I'll update the docs. Nice catch!
