### ISSUE TITLE
Broken references at README

### ISSUE THREAD

**Issue by icaropires** [mozilla-services/fx-sig-verify#75]
There're some broken references at the README that may confuse first time readers of the repository. They're `Lambda Installation` (two times) and `usage`

**Comment by hwine** [comment]
Good point about cleaning up the README for first time viewer. However, I'm more inclined to point folks to read-the-docs, where the links are correctly rendered.

Let me think about that a bit -- my rST is getting rusty, so another choice is to move to markdown.
